[approval]
always_ask = [ '.env' ]
auto_allow = []
mode = 'review'
worktree_auto_approve = true

[arcade]
enabled = true

[behavior]
allow_hyperlinks = true
audible_bell = false
confirm_close = true
mouse_autohide = true
restore_session = false
scroll_on_keystroke = true
scroll_on_output = false
scrollback_lines = 10000

[cursor]
blink = true
shape = 'block'

[diff]
context_lines = 3

[editor]
file_open_mode = 'builtin'
font_family = 'JetBrainsMono Nerd Font'
font_size = 17
show_hidden_files = true
word_wrap = true

[font]
bold_is_bright = true
family = 'JetBrainsMono Nerd Font'
size = 17

[notifications]
background_grace_seconds = 0
command_failed = true
enabled = true
finished = false
long_running_command = true
long_running_threshold_seconds = 30
needs_input = false

[shell]
args = []
default_cwd = '~'
program = ''

[theme]
name = 'catppuccin-mocha'

[window]
enable_blur = true
opacity = 0.95645065539513685
padding = 8